### ISSUE TITLE
Add width and height if size is not specified

### ISSUE THREAD

**Issue by exKAZUu** [WillBooster/markdown-it-img-size#3]
If no size specification like `200%:200%` is given, add `width` and `height` attributes by investigating the actual size of the given image.

**Comment by gumfum** [comment]
We can get the actual size of the given image from `naturalWidth` `naturalHeight` properties. I will try this way.
Example: https://lab.syncer.jp/Web/JavaScript/Snippet/35/

**Comment by exKAZUu** [comment]
たぶん、 `naturalWidth` / `naturalHeight` はブラウザ上で実際に描画しないと取得できない気がする。（もし取得できたらおけ）。
おそらく、 https://github.com/image-size/image-size とかを使って画像のサイズの取得が必要。
